### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by ddkwork** [markpatterson27/Codespaces-VNC-Image#6]
How to connect with vncview?

**Comment by markpatterson27** [comment]
When the codespace spins up, there should already be a port forwarded through the reverse proxy. Clicking on the local address 'Open in Browser' option should open a second tab with noVNC running in it. This will then connect to the VNC server running in the codespace.

![image](https://user-images.githubusercontent.com/35724907/173828402-e76f0b3e-3e11-4f96-9d19-2024f9a3944e.png)

This is setup with a minimal desktop. I was using this to teach tkinter to a few students and didn't want anything else available to them. There may be alternatives that are better for your use case, such as [Gitpod with VNC](https://github.com/gitpod-io/workspace-images/) or there is a [VNC option for devcontainers](https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/desktop-lite.md) which can be used with Codespaces.

Does this answer your question?

**Comment by ddkwork** [comment]
> When the codespace spins up, there should already be a port forwarded through the reverse proxy. Clicking on the local address 'Open in Browser' option should open a second tab with noVNC running in it. This will then connect to the VNC server running in the codespace.
> 
> ![image](https://user-images.githubusercontent.com/35724907/173828402-e76f0b3e-3e11-4f96-9d19-2024f9a3944e.png)
> 
> This is setup with a minimal desktop. I was using this to teach tkinter to a few students and didn't want anything else available to them. There may be alternatives that are better for your use case, such as [Gitpod with VNC](https://github.com/gitpod-io/workspace-images/) or there is a [VNC option for devcontainers](https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/desktop-lite.md) which can be used with Codespaces.
> 
> Does this answer your question?

thank you

**Comment by ddkwork** [comment]
has some way install windows on codespace?

**Comment by markpatterson27** [comment]
Codespaces are linux only.
